# -*- coding: utf-8 -*-
# Ã‚Â© 2016 ACSONE SA/NV (<http://acsone.eu>)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
    "name": "Advanced Multi-Company Bill Pay",
    "summary": "Advanced Multi-Company Bill Pay",
    "version": "10.0.6",
    "category": "Uncategorized",
    "website": "https://vetzip.vitalpet.net/",
    "author": "VitalPet",
    "depends": ['base','mail','web','product','account','account_asset','purchase','fetchmail', 'vitalpet_additional_fiscal_periods','account_payment_partner','vitalpet_supplier_enhancement'],
    "data": [
            'security/billpay_security.xml',
            'security/ir.model.access.csv',
            'data/billpay_data.xml',
            'data/ir_sequence_data.xml',
            'views/billpay_config.xml',
            'views/res_company.xml',
            'views/res_partner.xml',            
            'wizard/hold_reason.xml',
            'wizard/refuse_reason.xml',
            'wizard/reject_reason.xml',
            'wizard/popup_image.xml',
            'wizard/add_existing_bill.xml',
            'wizard/add_to_existing_doc.xml',
            'wizard/billpay_reversal.xml',
            'wizard/reverse_apply_credit.xml',
            'views/account_view.xml',
            'views/billpay_view.xml',
            'views/billpay_bills_view.xml',
            'views/acc_payable_receivable.xml',
            'views/dashboard_view.xml',
            'views/billpay_menuitems.xml',
            'views/bill_pay_attachment.xml',
            'bill_pay.xml',
    ],
    'qweb': ['static/xml/dashboard.xml',
            'static/xml/bill_inbox.xml'],
    'installable' : True,
    'auto_install' : False,
    'application' : True,
}
